// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesAppData.Data;

#nullable disable

namespace SalesAppData.Migrations
{
    [DbContext(typeof(SalesAppDbcontext))]
    [Migration("20221116094419_CreateSalesDb")]
    partial class CreateSalesDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SalesApp.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("product_Brand")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("product_description")
                        .HasColumnOrder(4);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("product_image_url")
                        .HasColumnOrder(9);

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("product_ModelName")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("product_price")
                        .HasColumnOrder(6);

                    b.Property<decimal>("ReceivingPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("product_Receiving_Price")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
